### ISSUE TITLE
Incorrect merging of Nisekoi s02e11 by Coalgirls

### ISSUE THREAD

**Issue by mustang651** [gnoling/UnlinkMKV#13]
I have problems with s02e11 of Nisekoi in 1080p: http://coalgirls.wakku.to/9830/nisekoi-second-season
OP plays 2 times after merging (just black screen and audiio in the first time).Hash-sums are correct. There is no problems with other episodes of the show.

p.s. OP1 ED7 if I remeber it right.

**Comment by gnoling** [comment]
Looked into this a bit, I need to compare against some of the other episodes in this release I think.

At first glance it appears to be some sort of issue with the FLAC track and mkvmerge splitting it oddly enough.

**Comment by mustang651** [comment]
Maybe I should try to replace mkvtoolnix with the latest one?

**Comment by Shadowghost** [comment]
@gnoling Same problem here. If I play the file with VLC it just jumps from the beginning of "Opening" chapter to the end of the same and plays the OP1 while being in the main episode chapter. It seems like some timestamps get mixed up.
Edit: @mustang651 switchign to latest mkvtoolnix doesn't change anything. If you try, don't forget to delete locals because otherwise UnlinkMKV won't find the chapters.

**Comment by hilts-vaughan** [comment]
There's some issues with the files. I actually wanted to unlink this release last week and was having trouble. Eventually, I came up with a bruteforce solution in native .NET that dealt with it. It's implemented @ https://github.com/hilts-vaughan/UnlinkMKV-GUI/releases/tag/0.2.1 which does some linear re-ordering, in case anyone else has this problem.

Be sure to tick off "Native Mode" in the GUI.

**Comment by gnoling** [comment]
Like I said, it's an issue with the FLAC tracks and splitting them. I can't imagine the work-around for this being anything remotely sane tbh.

**Comment by hilts-vaughan** [comment]
The workaround is not sane. :)
