### ISSUE TITLE
Missing Segments

### ISSUE THREAD

**Issue by sxzero** [gnoling/UnlinkMKV#21]
Hi!

I'm using windows 10 with strawberry Perl and always unlinkmkv shows the same error "missing segments!".

Log:
C:\unlinkmkv>unlinkmkv -fs -fa -fv --outdir "UMKV" "spice_and_wolf_08.mkv"
UnlinkMKV
      Options
         chapters: 1
         ffmpeg: x:\unlinkmkv\ffmpeg\bin\ffmpeg.EXE
         fix-audio: 1
         fix-subtitles: 1
         fix-video: 1
         fix_audio: 0
         fix_subtitles: 1
         fix_video: 0
         ignoredef: 0
         mkvext: x:\unlinkmkv\mkvtoolnix\mkvextract.EXE
         mkvinfo: x:\unlinkmkv\mkvtoolnix\mkvinfo.EXE
         mkvmerge: x:\unlinkmkv\mkvtoolnix\mkvmerge.EXE
         out_dir: x:\unlinkmkv\UMKV
         outdir: UMKV
         tmpdir: x:\unlinkmkv\UMKV\tmp
   processing x:\unlinkmkv\spice_and_wolf_08.mkv
      checking if file is segmented
         x:\unlinkmkv\spice_and_wolf_08.mkv contains segmented chapters
      generating chapter file
         loading chapters
         [EXT]
        ChStart 00:00:00.000000000
        ChEnd   00:01:29.590000001
        Offset  00:01:29.590000001
        OffTE   00:01:29.590000001
        ChEn    1
         [INT]
        ChStart 00:01:29.590000002
        ChEnd   00:22:9.537000002
        Offset  00:01:29.590000001
        OffTE   00:22:9.537000002
        ChEn    1
         [EXT]
        ChStart 00:22:9.537000002
        ChEnd   00:23:39.335000003
        Offset  00:02:59.388000002
        OffTE   00:23:39.335000003
        ChEn    1
         [INT]
        ChStart 00:23:39.377000003
        ChEnd   00:23:44.298000003
        Offset  00:02:59.388000002
        OffTE   00:23:44.298000003
        ChEn    1
      writing chapter temporary file
      looking for segment parts
      checking that all required segments were found
      missing segments!

I tried with another files and always is the same. I used the mkvtoolnix and ffmpeg files of the package and I downloaded too the lastest versions of the developer homepage but in both cases the error persist.

**Comment by Cervoz** [comment]
Hi,

Same problem here. No solution since?

**Comment by KucharczykL** [comment]
This is an old issue but recently I've encountered it too and I was really annoyed that it didn't work because ordered chapters mess with a lot of things from players to extracting subtitles, so I spent around 3 hours debugging this (I have literally zero experience with Perl so it took some time).

The issue, in my case, turns out to be non-English locale. UnlinkMKV parses output of mkvinfo and if it's not English, it doesn't find the UID of the segment and fails. To fix this on the user's side, just add LANG=en_US.UTF-8 in front of the command. This overrides the locale _only for that one command_, so you don't have to change it permanently:

`LANG=en_US.UTF-8 unlinkmkv file.mkv`

However, I have no idea how to solve this permanently from within the script, like I said I don't know any Perl. Ideally, there would be a way that doesn't rely on parsing the output but manages to get the info regardless of language.

**Comment by gnoling** [comment]
Yeah, this has been reported before -- the script does rely on MKVtoolnix CLI tools, which itself changes it's output based on language settings. I could try forcing the locale but that's a slippery slope to deal with. Likewise, at some point mkvtoolnix had adjusted it's formatting and that broke things as well.

Perhaps middle of the road here would be for me to take some time and update the README to mention this issue.

**Comment by KucharczykL** [comment]
Just found out about `mkvinfo --ui-language en_US`. Would that be a more elegant solution?

**Comment by gnoling** [comment]
Commit 51079dc closes #21
